### ISSUE TITLE
Update critical dependencies

### ISSUE THREAD

**Issue by hblitza** [virtualcitySYSTEMS/vcs-oblique#4]
Hi,
we use this lib in masterportal-context and stumbled upon outdated versions. `axios` <= 0.21.1 for instance (cf. https://github.com/advisories/GHSA-cph5-m8f7-6c5x).  
Are you still maintaining this repo and if so, could you upgrade the dependencies?  
Cheers! Hannes

**Comment by jbo023** [comment]
Hi Hannes, 

The axios version range already includes all minor Versions, so npm i vcsOblique installs the newest axios. An npm audit fix should solve this.

Cheers, 
Jannes

**Comment by hblitza** [comment]
Allright thanks!
